apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
        app: spring-boot-k8s
    replicas: 2
    template:
        metadata:
          labels:
            app: spring-boot-k8s
        spec:
          containers:
            - name: spring-boot-k8s
              image: root2codegunz/jenkinstest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8100

---

apiVersion: apps/v1
kind: Service
metadata:
  name: spring-boot-k8-service
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8100
      targetPort: 8100
  type: NodePort